default: &default
  auth0_client_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_client_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>
  sendgrid_user: <%= ENV['SENDGRID_USER'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  <<: *default
  secret_key_base: f48730d547992e3627228cd05247b36644106e9f73d649ddbd1a6ef1ed0773b7f1d8e81752f929d7093d55706bd65b88f283c773d2053394d7c1e42dfb519234

test:
  <<: *default
  secret_key_base: c79adc4fa2bc648d5f85f19ef48374ba47e5ba15c347c10a2c526e652bc6985fe72cf1ee220db67ea2ccecf054bdc9200b26cf237eed5c3f0817ca7c0eba8920

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
